{
 "title": "uwsgi",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "harakiri count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "harakiri count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uwsgi_workers",
     "select": [
      [
       { "params": [ "harakiri_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "listen queue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uwsgi_workers",
     "query": "SELECT sum(\"listen_queue\") FROM \"uwsgi_overview\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "harakiri_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "worker status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "idle",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "uwsgi_workers",
     "query": "SELECT count(\"status\") FROM \"uwsgi_workers\" WHERE $timeFilter and \"status\"='idle' GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "harakiri_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "cheap",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"status\") FROM \"uwsgi_workers\" WHERE  $timeFilter and \"status\"='cheap' GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "busy",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"status\") FROM \"uwsgi_workers\" WHERE  $timeFilter and \"status\"='busy' GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "worker avg request time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "worker_id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uwsgi_workers",
     "query": "SELECT mean(\"avg_rt\") FROM \"uwsgi_workers\" WHERE $timeFilter GROUP BY time($__interval), \"worker_id\" fill(null)",
     "select": [
      [
       { "params": [ "avg_rt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "worker requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uwsgi_workers",
     "query": "SELECT mean(\"requests\") FROM \"uwsgi_workers\" WHERE $timeFilter GROUP BY time($interval), \"worker_id\"",
     "select": [
      [
       { "params": [ "harakiri_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "in_request sum",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uwsgi_workers",
     "query": "SELECT sum(\"in_request\") FROM \"uwsgi_cores\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "harakiri_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "worker amount",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "workers 1-4 total amount",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uwsgi_workers",
     "query": "SELECT count(\"avg_rt\") FROM \"uwsgi_workers\" WHERE $timeFilter AND (\"worker_id\"='1' OR \"worker_id\"='2' OR \"worker_id\"='3' OR \"worker_id\"='4') GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "harakiri_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "workers 5-8 total amount",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"avg_rt\") FROM \"uwsgi_workers\" WHERE $timeFilter AND (\"worker_id\"='5' OR \"worker_id\"='6' OR \"worker_id\"='7' OR \"worker_id\"='8') GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "workers 9-10 total amount",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"avg_rt\") FROM \"uwsgi_workers\" WHERE $timeFilter AND (\"worker_id\"='9' OR \"worker_id\"='10' OR \"worker_id\"='11' OR \"worker_id\"='12') GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "respawn count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uwsgi_workers",
     "query": "SELECT sum(\"respawn_count\") FROM \"uwsgi_workers\" WHERE $timeFilter GROUP BY time($interval), \"uwsgi_host\"",
     "select": [
      [
       { "params": [ "harakiri_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "load sum",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uwsgi_workers",
     "query": "SELECT sum(\"load\") FROM \"uwsgi_overview\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "harakiri_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "running time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uwsgi_workers",
     "query": "SELECT mean(\"running_time\") FROM \"uwsgi_workers\" WHERE  $timeFilter GROUP BY time($interval), \"worker_id\"",
     "select": [
      [
       { "params": [ "harakiri_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  }
 ]
}